# Generated by Django 4.1.5 on 2023-01-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('fnm', models.CharField(max_length=30)),
                ('lnm', models.CharField(max_length=30)),
                ('sal', models.FloatField()),
            ],
        ),
    ]
